### ISSUE TITLE
Reverse the color scheme on the breakpoint

### ISSUE THREAD

**Issue by kevinbrandon** [idanarye/vim-vebugger#13]
Have issues with color scheme with the breakpoint. Would be cool if it reversed the color's with its own highlight option so that it didn't interfere with peoples color schemes.

**Comment by vbh29** [comment]
It would be great to have color reversal for the line being executed also since currently I don't see the current line pointer (I have line numbers enabled so I am not sure if this has to do with that)

It would also be great to have something similar to a quickfix/scratch buffer to view local variables / examine other expressions like lists.

**Comment by idanarye** [comment]
@vbh29 I really don't like the idea of having both the current executed line and the breakpoints use the same highlight style. Executed line should be fine with simply bolding it, since you jump to it anyways when you stop on it.

As for buffer for special stuff, I was already thinking about something like this for showing watchers and maybe for the call-stack. Still thinking about the design though...

**Comment by idanarye** [comment]
@kevinbrandon I'm having second thoughts about inversing the breakpoints colors - it just looks plain ugly. `ColorColumn` produces decent looking highlight on all built-in colors. I'm gonna change it so if there is a color group called `BreakPoint` it'll use it and if there isn't i'll use `ColorColumn`.

**Comment by kevinbrandon** [comment]
Yeah I looked at other color schemes and its can look horrid. The reasoning though for the inverse was that you can have a color scheme like the one I am using that you cant see anything at all with because it made it a red font on a red background. Maybe BreakPoint should go with something like chrome uses a light blue background and all white for the foreground. At least playing around with http://vimcolors.com/ and using the mouse hightlight to see it seemed like that color scheme works well.

**Comment by kevinbrandon** [comment]
Or better yet ...

from http://andrewradev.com/2011/08/06/making-vim-pretty-with-custom-colors/

Visual: This one is for highlighting the visual selection. I'd recommend aiming for good contrast with a bright background color.

```
diff --git a/autoload/vebugger/std.vim b/autoload/vebugger/std.vim
index d98758e..549c91f 100644
--- a/autoload/vebugger/std.vim
+++ b/autoload/vebugger/std.vim
@@ -235,10 +235,8 @@ function! s:standardCloseHandlers.removeCurrentMarker(debugger) dict
     sign unplace 1
 endfunction

-highlight BreakPoint term=reverse cterm=reverse gui=reverse     
-
-sign define vebugger_current text=->
-sign define vebugger_breakpoint text=** linehl=BreakPoint
+sign define vebugger_current text=-> linehl=Visual
+sign define vebugger_breakpoint text=**
```

![2015-04-14-190302_496x68_scrot](https://cloud.githubusercontent.com/assets/8398598/7151060/6c91f262-e2d9-11e4-9b82-0eb5c5e946a7.png)

![2015-04-14-190556_729x75_scrot](https://cloud.githubusercontent.com/assets/8398598/7151061/71a3f462-e2d9-11e4-9c5f-adfa7fab1296.png)

Hows that?

**Comment by idanarye** [comment]
Reversed highlight indeed makes the line noticeable, but just doesn't scream "breakpoint" like `ColorColumn` does...

What color scheme are you using that `ColorColumn` looks bad on?

**Comment by kevinbrandon** [comment]
The default.  This is what it looks like with ColorColumn

![2015-04-15-084155_721x66_scrot](https://cloud.githubusercontent.com/assets/8398598/7162787/6a34a07e-e34b-11e4-9993-e3f17b962ae1.png)

As you can see the code that was in red blends in with the background. 

Another one that doesn't work is peachpuff

![2015-04-15-084817_727x62_scrot](https://cloud.githubusercontent.com/assets/8398598/7162943/3eac2a34-e34c-11e4-9cf7-7b37f94aed47.png)

same problem... just problematic when the color is the same as the highlight. Thats why I went with the inverse... garaunteed but it is ugly. The latest pull request I put in uses Visual (which does the same highlight as when you do a visual selection ^v, that can be problematic too though).

Thats why I made the comment that maybe it should just be BreakPoint color group that doesnt inverse but forces a background and a foreground. Seemingly Google choose with chrome a scheme like that with highlighting in the browser...

![2015-04-15-085357_591x76_scrot](https://cloud.githubusercontent.com/assets/8398598/7163121/2945c064-e34d-11e4-8022-117933da1196.png)

Seems like that approach works with everything... where it fails a bit is if the background is already the same as your highlight background color. For chrome as an example http://www.w3schools.com/tags/ref_color_tryit.asp?color=RoyalBlue it seems like that if you highlight with the mouse there you cant see the the background hightlight but the text does turn white. If the text was already white, well you wouldnt see any highlight but at least you can read the code.

I agree with a color that screams breakpoint like red... would red background with black text foreground work? Can't imagine many people use red background at all...

**Comment by idanarye** [comment]
Dear god what kind of terminal are you using? I've checked with gVim and with Konsole and `ColorColumn` looks good in both `default` and `peachpuff`...

At any rate, using a constant color highlight might be a reasonable comparison. I hate to loose syntax highlighing, but it shouldn't be a problem to make it configurable...

So, the question is - use `ColorColumn` and force those that use crappy terminals to specify the hightlight they want? Or use constant colors and allow those who want to configure better-looking colors?

**Comment by kevinbrandon** [comment]
haha just using terminator and tmux. Cool I guess your idea of using ColorColumn makes sense but use BreakPoint if defined by the user.
