### ISSUE TITLE
Node Debugger

### ISSUE THREAD

**Issue by jalcine** [idanarye/vim-vebugger#2]
I figured it'd be cool to have support for the [Node Debugger](http://nodejs.org/api/debugger.html) as well. I can start peeking at how you've implemented the others and work from there.

Update: Might take some notes from [`node-vim-debugger`](https://github.com/sidorares/node-vim-debugger)

**Comment by idanarye** [comment]
Give it a go. I've claimed my framework is flexible enough to easily add support for new debuggers - I'm eager to see if I was right!

**Comment by i-oliva** [comment]
Will love to see!

**Comment by jalcine** [comment]
I haven't had the time myself to work on this. That combined with the fact that my daily stack works more with the Web-excuted form of JavaScript vs native machine execution had me lose interest in this.

If someone is willing + able, I'm down to collab / code review.

**Comment by daniellmorris** [comment]
I just submitted a PR for this. I have been using it for my own work for the past month.

**Comment by daniellmorris** [comment]
The PR was merged. So this should be able to be closed.

**Comment by idanarye** [comment]
Yea... you need to put `close #2` or [something similar](https://help.github.com/articles/closing-issues-using-keywords/) in the commit message to make it close automatically when the PR gets merged.
