### ISSUE TITLE
Execute arbitrary debugger commands

### ISSUE THREAD

**Issue by IngoMeyer441** [idanarye/vim-vebugger#28]
Hey,
thanks for the great work. :) Is it possible to send arbitrary commands to the debugger (in my case gdb)? I would like to use the `backtrace` command to see the whole stack trace when my program died with a segmentation fault.

**Comment by idanarye** [comment]
Yes - see `:help vebugger-open-the-hood`. Basically, you use `:VBGtoggleTerminalBuffer` to open a buffer that shows the direct interaction with the terminal, and :VBGrawWrite`/`:VBGrawWriteSelectedText` to send text to it.

Keep in mind that Vebugger runs GDB in [Machine Interface Mode](https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI.html), so the output may look a bit weird.

**Comment by IngoMeyer441** [comment]
I should have read your documentation better... Everything is explained there but I skipped it inadvertently. Thanks for your explanation!
