### ISSUE TITLE
Doesn't seem to work for Windows/Cygwin/.NET

### ISSUE THREAD

**Issue by aikeru** [idanarye/vim-vebugger#3]
I am using cygwin on Windows with .NET (as opposed to Mono). I am using cygwin vim. Everything is 32-bit on this system.
I have Mdbg downloaded and included in the path.

If I try to run an executable like so:
1. Create a console app
2. Navigate to same folder as .csproj
3. Start debugger with 
   `:call vebugger#mdbg#start('./bin/Debug/<exefilename>.exe', {})`

Mdbg.exe does start in the background but I don't see anything in vim and I don't see the console application in the list of processes nor do I see any window for it.

If I start the console application ahead of time and then start vebugger like so:
`:call vebugger#mdbg#start('./bin/Debug/<exefilename>.exe', { 'pid':'<pidnum>' })`
Mdbg.exe starts, but functionality seems to be very limited.

If I set a breakpoint, the program seems to stop at the breakpoint, and I can continue from there. It does not seem to highlight the current line executing.

Also, I cannot seem to eval or execute.
For example:

`:VBGeval Console.WriteLine("ok");`

Does not seem to do anything and if I have

```
Console.WriteLine("ok");
```

selected in visual mode I run

```
:'<,'>VBGexecuteSelectedText
```

but seems to have no effect.

Should this be expected to work in .NET on Windows in Cygwin? How much functionality works?
I am still somewhat new to vim, so perhaps I am doing something wrong?

I really appreciate your help :)

**Comment by idanarye** [comment]
I've never actually used Cygwin so I never tested Vebugger in it, but my first guess is a paths problem(POSIX vs Windows path styles). Can you try running it with Windows path styles

``` vim
:call vebugger#mdbg#start('.\bin\Debug\<exefilename>.exe', {})`
```

and see what happens?

Also, please run this command:

``` vim
:call vebugger#mdbg#start('./bin/Debug/<exefilename>.exe', {}) | :VBGtoggleTerminalBuffer
```

and post here what's written on the terminal buffer.

Finally, I want to see how the paths are translated internally, so please post the results of

``` vim
echo shellescape(fnamemodify('.\bin\Debug\<exefilename>.exe',':p'))
echo shellescape(fnamemodify('.\bin\Debug\<exefilename>.exe',':p'))
```

As for evaluating and executing - these features are quite limited in MDbg. There is no command execution - only variable setting, so I translate `:VBGexecute ...` to `set ...` - e.g. `:VBGexecute x = 12` translates to `set x = 12` - but this doesn't work for functions.

Same for evaluation - I actually use the `print` MDbg command, which can only print variables.

I might someday change it(MDbg also has the `funceval` command, but it requires fully qualified names, and I'll have to parse the command to see if it's a function call or a variable assignment/printing...)

**Comment by aikeru** [comment]
Sure! I'd love to help in any way I can contribute. As soon as I get a chance I'll try and let you know. Thanks for the informative reply too and for creating this and sharing it with the world :)

**Comment by aikeru** [comment]
Here is the output of the command 

```
:call vebugger#mdbg#start('./bin/Debug/<exefilename>.exe', {}) | :VBGtoggleTerminalBuffer
```

was the following

```

when StepComplete do where
when BreakpointHit do where
mode nc on
run '/home/Michael/scratch/sample/bin/Debug/test' 0
where
MDbg (Managed debugger) v0.0.0.0 started.

Copyright (C) Microsoft Corporation. All rights reserved.



For information about commands type "help";

to exit program type "quit".



mdbg> mdbg> mdbg> mdbg> Error: The specified executable ''/home/Michael/scratch/sample/bin/Debug/test.exe'.exe' could not be found.

mdbg> Error: No active process


```

I tried chopping off the extension (.exe) from the filename, but it didn't seem to fix the issue.
I suspect it's just some issue with parsing/concatenating the filename and passing it to mdbg.
Also, I did try the following but none of them worked (as you might expect due to output above) after copying the files to an appropriate location:

```
:call vebugger#mdbg#start('/cygdrive/c/Scripts/testexe/test.exe', {})
:call vebugger#mdbg#start('c:\\Scripts\\testexe\\test.exe', {})
:call vebugger#mdbg#start('c:\Scripts\testexe\test.exe', {})
:call vebugger#mdbg#start('.\\bin\\Debug\\test.exe', {})
:call vebugger#mdbg#start('.\bin\Debug\test.exe', {})
:call vebugger#mdbg#start('./bin/Debug/test.exe', {})
```

I did look into some of the vimscript but I don't know vimscript and wasn't sure where I might try to assist with the filename argument passing.

**Comment by aikeru** [comment]
Please notice in particular the .exe'.exe part... :)

**Comment by aikeru** [comment]
Also here is the output of the command

```
echo shellescape(fnamemodify('.\bin\Debug\<exefilename>.exe',':p'))
```

```
'/home/Michael/scratch/sample/bin/Debug/test.exe'
```

which is correct (ls with that path returns one exe file)

**Comment by idanarye** [comment]
OK - this certainly looks like a paths problem. Vim inside Cygwin uses the POSIX path style, but MDbg is probably expecting Windows path styles - and I'm not even sure if it can recognize `/home/...`, even if you run it from Cygwin.

Seems like debug-over-ticket-opener protocol won't do here - I'll have to install Cygwin on my machine to make this work. I'll try to make time for it...

**Comment by aikeru** [comment]
Thanks for taking some time to respond and look into this issue... if I get a chance I will see what I might be able to do. 
Can you tell me where this plugin passes the file name to mdbg?

**Comment by aikeru** [comment]
Also.. I dont know if you want to put something cygwin specific into the plugin but this may help...

https://cygwin.com/faq/faq.html#faq.using.converting-paths

**Comment by idanarye** [comment]
This is the line that sends the exe path to MDbg:
https://github.com/idanarye/vim-vebugger/blob/develop/autoload/vebugger/mdbg.vim#L29

I'll look at `cygpath` - Cygwin is popular enough to get special treatment. I also need to see how the other debuggers handle paths when ran inside Cygwin.

**Comment by aikeru** [comment]
I don't mean to spam, but I find that the test executable does start successfully if I change this line:

```
call l:debugger.writeLine('run '.shellescape(fnamemodify(a:binaryFile,':p')).' '.vebugger#util#commandLineArgsForProgram(a:args))
```

to the following

```
call l:debugger.writeLine('run c:\Scripts\testexe\test.exe')).' '.vebugger#util#commandLineArgsForProgram(a:args))
```

...assuming the files are copied to the correct location.

**Comment by idanarye** [comment]
`cygpath` seems to be able to handle this conversion.

**Comment by idanarye** [comment]
OK, I've solved this in a new branch - [feature/fix-cygwin-paths](https://github.com/idanarye/vim-vebugger/tree/feature/fix-cygwin-paths). @aikeru, please check that it works for you so I can merge&release it.

**Comment by aikeru** [comment]
As soon as I get the chance will try and report back :)

**Comment by aikeru** [comment]
@idanarye looks so much better! 

Breakpoints now show up when I set them for a specific line and the executable runs when I start the debugger with a relative path like ./bin/Debug/hellosample.exe
There might be some other issues to discover, but this branch was a success! :) Thanks so much! Please merge & release...

![debugger-progress](https://cloud.githubusercontent.com/assets/1163405/5752742/24e9d798-9c4a-11e4-8dfe-ea5b821631da.PNG)
