### ISSUE TITLE
absolute file paths for breakpoints should not contain "~"

### ISSUE THREAD

**Issue by IngoMeyer441** [idanarye/vim-vebugger#39]
Hey,
when setting breakpoints, file paths that are not a subpath of the current working directory are expanded to an absolute path containing `~` for the user home directory. It seems as if neither GDB nor LLDB can handle `~` properly. Wouldn't it be better to use a path without `~`?
The `expand` call in [line 15 in `plugin/vebugger.vim`](https://github.com/idanarye/vim-vebugger/blob/develop/plugin/vebugger.vim#L15) could be changed from
```vim
expand('%:~:.')
```
to
```vim
expand('%:p:.')
```

**Comment by idanarye** [comment]
BTW, @IngoHeimbach, if you have a solution you can just send a PR. That way you'll have your name on it...
