### ISSUE TITLE
Does this require a specific version of vim 

### ISSUE THREAD

**Issue by nanocore** [idanarye/vim-vebugger#5]
I am using vim 7.3.515 and trying to use vebugger with jdb to debug a java program.  I have gone throught the startup guide and gone through the code a bit, but it won't start.  I keep getting errors about unknown function "s:read...".  That is, the vebugger#jdb#start is executing and calls the addHandler with each of the s:read... functions.  Then it begins to run and in the s:f_debugger.handleLine where it loops over the readHandlers it throws up the error and repeats for each of the s:read... functions that are added in the addHandlers. 

Thinking it was something specific to jdb, I compiled a simple c program and then used the VBGstartGDB and got the exact same errors.  

The only thing  I have for vebugger in my .vimrc is the setting of g:vebugger_leader
I have the most recent vimproc compiled and installed.

Any hints as to why it doesn't know about the functions?  Seems like I am missing something...

**Comment by idanarye** [comment]
I develop on the 7.4. I just compiled 7.3.515 and I encounter these errors, but I still need to figure exactly which new feature of 7.4 I depend on.

**Comment by nanocore** [comment]
And I did the same and compiled the 7.4 and it ran just fine.  Before doing this I did get it to work with my older 7.3 version by changing the functions in the autoload/vebugger/jdb.vim from s:read... and s:write.. etc to g:jdbread... and g:jdbwrit...  Essentially making each of the functions that get passed into addHandlers be global and unique by prepending jdb to each of them.  This way when the handle call is made  each of these it does know about them.  Not that this is what you intended, but it does get past that error about unknown function.

Also, there is another place, in autoload/vebugger/std.vim in the function
updateMarksForFile
there is something that it didn't like about the 3rd line 
exe 'sign unplace \* ...
I changed it to be exe ':sign unplace *'  (ie, and got rid of the rest of the line) 
and it shut the error up (ie, it didn't show anymore) and it looked like everything about the sign was OK.

**Comment by idanarye** [comment]
Yea, I did some tests myself and it does look like in 7.3 you can only run funcrefs to `s:` functions from the file where they are declared. That'll mean I'll have to rename all the handlers...

As for `sign unplace` - it seems like I can't use `*` if I want to limit it to a single file. No biggie - I can simply call it twice(I only use IDs 1 and 2).

**Comment by idanarye** [comment]
@nanocore I've made the changes in the branch  `feature/fix-for-vim7.3`. Please test that it works for you so I can merge it and release a bugfix.

**Comment by nanocore** [comment]
I have tested the fix branch with both vim 7.3 and 7.4 with success.  Both experiences were identical, so I would say that your fix is correct. Thanks!

My iPhone sent this ...

**Comment by idanarye** [comment]
We're good to merge then.
