### ISSUE TITLE
Showing object content with JDB

### ISSUE THREAD

**Issue by shadowphoenixpt** [idanarye/vim-vebugger#86]
I'm trying to find a way to show an object contents using vebugger. When I use VBGeval I only get a small description of the object, but not the variable of its fields. If I use VBGrawWrite and use the dump on the object, I get its content on the JDB console but only the first line on vim.

Would it be possible or is there any way for me to adapt this plugin in a way that I could get the object content without using VBGrawWrite and the JDB console?

**Comment by idanarye** [comment]
Vebugger uses JDB's `eval` command to show objects. I could use the `dump` command instead, but then it wouldn't show container objects as nicely...
Maybe a combination? Use both commands, and show the output of `eval` followed by that of `dump`?

**Comment by shadowphoenixpt** [comment]
> Vebugger uses JDB's `eval` command to show objects. I could use the `dump` command instead, but then it wouldn't show container objects as nicely...
> Maybe a combination? Use both commands, and show the output of `eval` followed by that of `dump`?

A combination sounds like a great idea :)
