### ISSUE TITLE
Node Help

### ISSUE THREAD

**Issue by parker789** [idanarye/vim-vebugger#87]
Hey, first off - I'm new to vim debugging! I've been using vim for a few years, but honestly never tried to customize things to work with language servers like VSCode does.  I'm trying to change that around and give your debugger a go for NodeJS debugging.. but I'm a bit lost.

In VSCode I need to start my server using the --inspect flag, `npm start --inspect` which will exec my startup script and also debugging server listening on ws://127.0.0.1:9229/... and then I need to attach to that within VSCode.. it all works fine.

If possible I'd like to mimic this with your tool inside vim. I'm trying `:VBGstartNInspect src/app.js` but its not working - anyway you can give me some help?

**Comment by parker789** [comment]
Anyone successfully using this with an attached node debugger?

**Comment by opensourcegeek** [comment]
@parker789 Did you find a solution?

**Comment by parker789** [comment]
@opensourcegeek no, and I unfortunately stopped working on a vim solution

**Comment by opensourcegeek** [comment]
@parker789 Ok, I've got the inspect to start and stops at the breakpoint, I'm currently having trouble to "eval" any expression though!
